# ===================================
# Author: @aglorhythm / girlysheet.cloud ✿
# Description: This script is retrieved by azure pipelines.
# The docker image is build and pushed in another azure pipeline. 
# I cannot add different environments because of budget purpose
# ===================================

trigger:
  branches:
    include:
    - main

variables:
  - group: TofuSecrets
  TF_ROOT: $(Build.SourcesDirectory)/tofu
  TF_BUCKET: $(Build.SourcesDirectory)/tofu/scripts
  ANS_ROOT: $(Build.SourcesDirectory)/ansible
  ANS_INVENTORY: $(Build.SourcesDirectory)/ansible/resources
stages:
- stage: Validate
  jobs:
  - job: tofu_validate
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        cd $(TF_BUCKET)
        echo "Changed directory:" 
        pwd
        tofu init -input=false
        tofu validate
    - script: |
        cd $(TF_BUCKET)
        echo "Changed directory:" 
        pwd
        tofu init -input=false
        tofu validate
    displayName: 'Validate Tofu deployment'
    continueOnError: false

- stage: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: tofu_plan
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        cd $(TF_BUCKET)
        echo "Changed directory:" 
        pwd
        tofu init -input=false -reconfigure
        tofu plan -refresh=true -out=tfplan_bucket"
        ls -lah
      displayName: 'Plan Tofu changes - Bucket'
      continueOnError: false

    - script: |
        cd $(TF_ROOT)
        echo "Changed directory:" 
        pwd
        tofu init -input=false -reconfigure
        tofu plan -refresh=true -out=tfplan_root"
        ls -lah
      displayName: 'Plan Tofu changes - Root'
      continueOnError: false

    - publish: $(TF_BUCKET)/tfplan_bucket
      artifact: TofuPlanBucket
      displayName: 'Publish Tofu plan for the s3 bucket'

    - publish: $(TF_ROOT)/tfplan_root
      artifact: TofuPlanRoot
      displayName: 'Publish Tofu plan for the root script'

- stage: Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: tofu_apply
    pool:
        name: Default
    steps:
    - checkout: self
    - download: current
      artifact: TofuPlanBucket
      displayName: 'Download Tofu plan for the s3 bucket'

    - download: current
      artifact: TofuPlanRoot
      displayName: 'Download Tofu plan for the root script'

    - script: |
        cd $(TF_BUCKET)
        echo "Changed directory:" 
        pwd
        tofu init -input=false -reconfigure
        tofu apply tfplan_bucket
      displayName: 'Apply Tofu changes - Bucket'
      continueOnError: false

    - script: |
        cd $(TF_ROOT)
        echo "Changed directory:" 
        pwd
        tofu init -input=false -reconfigure
        tofu apply tfplan_root
      displayName: 'Apply Tofu changes - Root'
      continueOnError: false

    - script: |
        echo "New host file:" 
        ls $(Build.SourcesDirectory)/ansible
        cat $(Build.SourcesDirectory)/ansible/hosts
        echo "New group vars file:" 
        ls $(Build.SourcesDirectory)/ansible/${ENVIRONMENT}/group_vars
        cat $(Build.SourcesDirectory)/ansible/${ENVIRONMENT}/group_vars/*.yml
      displayName: 'Check new created resources'
      continueOnError: false

    - publish: $(Build.SourcesDirectory)/ansible
      artifact: AnsibleResources
      displayName: 'Publish Ansible resources'

- stage: Configure
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: ansible_configure
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        pwd
    displayName: 'Configure GS Server'
