# ===================================
# Author: @aglorhythm / girlysheet.cloud ✿
# Description: This script is retrieved by azure pipelines.
# The docker image is build and pushed in another azure pipeline. 
# I cannot add different environments because of budget purpose
# ===================================

trigger:
  branches:
    include:
    - main

variables:
  TF_ROOT: $(Build.SourcesDirectory)/terraform
  TF_BUCKET: $(Build.SourcesDirectory)/terraform/scripts
  ANS_ROOT: $(Build.SourcesDirectory)/ansible
  ANS_INVENTORY: $(Build.SourcesDirectory)/ansible/resources

stages:
- stage: Validate
  jobs:
  - job: terraform_validate
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        pwd
        ls
        cd $(TF_BUCKET)
        pwd
        ls
    displayName: 'Validate Deployment'

- stage: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: terraform_plan
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        pwd
    displayName: 'Plan Terraform Changes'

- stage: Apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: terraform_apply
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        pwd
    displayName: 'Apply Terraform Changes'

- stage: Configure
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  jobs:
  - job: ansible_configure
    pool:
        name: Default
    steps:
    - checkout: self
    - script: |
        pwd
    displayName: 'Configure GS Server'
