version: '3.8'
services:
  frontend:
    image: girlysheet.azurecr.io/aglorhythm/girlysheet-website:latest 
    ports:
      - "3001:3001"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    restart: unless-stopped

 